title: Indent
author:
  name: Someone
  email: hi@anindent.ml
description: > 
  a minimal standlone static blog template

show_excerpts: true

baseurl: ""
url: ""

tag_page_layout: tag_page
tag_page_dir: tag

staticmanUrl: https://less--app.herokuapp.com/v2/entry/anindent/anindent.github.io/master/comments
enableComments: true

minima:
  # skin: dark
  date_format: "%b %-d, %Y"
  permalink: /:year/:month/:day/:title:output_ext
  header_pages:
  - about.md
  - blog.md
  - contact.md

  # generate social links in footer
  social_links:
    twitter: indent
    github:  indent
    # devto: indent
    # dribbble: indent
    facebook: indent
    # flickr:   indent
    instagram: indent
    # linkedin: indent
    # pinterest: indent
    # youtube: indent
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: indent
    # googleplus: +indent
    # microdotblog: indent
    keybase: indent

    # Mastodon instances
    # mastodon:
    # - username: indent
    #   instance: example.com
    # - username: indent2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: indent
    #   instance: example.com
    # - username: indent2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-admin
 - jekyll-youtube
 - jekyll/tagging
 - jekyll-tagging-related_posts
 - jekyll-twitter-plugin
 - jekyll-spaceship
 - jekyll-giphy